### ISSUE TITLE
Exclude properties from diff

### ISSUE THREAD

**Issue by tomasbruckner** [weichch/system-text-json-jsondiffpatch#29]
Hi, is there a way to ignore properties from diff? The JsonDiffPatch does it here https://github.com/wbish/jsondiffpatch.net/blob/master/Src/JsonDiffPatchDotNet/JsonDiffPatch.cs#L332

What I am missing in the JsonDiffPatch is that it only allows you to exclude paths instead of properties which is a problem with recursive objects or arrays. To ignore property `foo` in an array of objects

```
{ "bar" : [ { "foo": 1 }, { "foo": 2 }, { "foo": 3} ] }
```

you would have to do

```
exclude paths: "bar.arr[0].foo", "bar.arr[1].foo", "bar.arr[2].foo"
```
This is useful in some scenarios, but it would be amazing if there would also be an option to exclude properties by their name
```
exclude properties: "foo"
```

The JsonDiffPatch looks abandoned so I am looking for an alternative that would support this scenario.

Is it something doable?

**Comment by weichch** [comment]
Ignoring properties is not currently not supported, but I do have plan to add this feature (hopefully next version), and it shouldn't be hard to do.

In a nutshell, I was planning to add a property filter like jsondiffpatch has [here](https://github.com/benjamine/jsondiffpatch/blob/ef38c5d97c349b0a3672c08710d1625307d3de94/src/index.d.ts#L163) in [`JsonDiffOptions`](https://github.com/weichch/system-text-json-jsondiffpatch/blob/main/src/SystemTextJson.JsonDiffPatch/Diffs/JsonDiffOptions.cs):

```
public Func<string, Context, bool>? PropertyFilter { get; set; }
```

A custom filter can get the property name and the diff context and return a boolean value to indicate whether to ignore the property.

I'm re-considering / restructuring the diff engine at the moment given my next priority is adding some support to `JsonDocument` diff. It will make clear sense to me how the `Context` can be defined to support both `JsonNode` and `JsonDocument` after this work.

**Comment by WojciechNagorski** [comment]
@weichch This would be great to have `PropertyFilter`.

**Comment by WojciechNagorski** [comment]
Any progress on `PropertyFilter`. It block me before using `SystemTextJson.JsonDiffPatch` and event entire `System.Text.Json`. Maybe I can help you with this feature?

**Comment by weichch** [comment]
Hi @WojciechNagorski I actually prioritized this a little bit because it will be taking a bit longer to add `JsonDocument` diff support. I've done the changes locally, which I pushed it up just now #30. I still need to add some tests before a stable version release, but I can release a preview version soon.

Do both of you and @tomasbruckner mind providing some test cases you'd like the property filter to cover?

**Comment by tomasbruckner** [comment]
@weichch that's great to hear!
Thanks for asking, it is very considerate!
For me, the example from the first post is sufficient.

**Comment by weichch** [comment]
Seems like there is a quirk in array diff where the property filter is not applied to array items, because the [the comparison](https://github.com/weichch/system-text-json-jsondiffpatch/blob/cb853ff9c60c7b5c4712fd0d4d12b5ab466d7f3d/src/SystemTextJson.JsonDiffPatch/Diffs/JsonDiffPatcher.Array.cs#L200) is done using `DeepEquals` not `Diff`. I tested `jsondiffpatch` also has the same issue. I'm working on a fix.

**Comment by WojciechNagorski** [comment]
For me it can works in the same way like in `JsonDiffPatch.Net`
